-- Schema for H2 Database
-- Alpacode Dashboard Users Table

CREATE TABLE IF NOT EXISTS USER (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    EMAIL VARCHAR(255) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255),
    NAME VARCHAR(100) NOT NULL,
    COMPANY_NAME VARCHAR(200),
    ROLE VARCHAR(20) NOT NULL,
    STATUS VARCHAR(20) NOT NULL,
    INVITE_TOKEN VARCHAR(255),
    INVITE_TOKEN_EXPIRY TIMESTAMP,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Index for faster email lookups
CREATE INDEX IF NOT EXISTS IDX_USER_EMAIL ON USER(EMAIL);

-- Index for invite token lookups
CREATE INDEX IF NOT EXISTS IDX_USER_INVITE_TOKEN ON USER(INVITE_TOKEN);

-- Index for role-based queries
CREATE INDEX IF NOT EXISTS IDX_USER_ROLE ON USER(ROLE);
