-- Schema for H2 Database
-- Alpacode Dashboard

-- ===========================================
-- Users Table
-- ===========================================
CREATE TABLE IF NOT EXISTS APP_USER (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    EMAIL VARCHAR(255) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255),
    NAME VARCHAR(100) NOT NULL,
    COMPANY_NAME VARCHAR(200),
    ROLE VARCHAR(20) NOT NULL,
    STATUS VARCHAR(20) NOT NULL,
    INVITE_TOKEN VARCHAR(255),
    INVITE_TOKEN_EXPIRY TIMESTAMP,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS IDX_APP_USER_EMAIL ON APP_USER(EMAIL);
CREATE INDEX IF NOT EXISTS IDX_APP_USER_INVITE_TOKEN ON APP_USER(INVITE_TOKEN);
CREATE INDEX IF NOT EXISTS IDX_APP_USER_ROLE ON APP_USER(ROLE);

-- ===========================================
-- Invoices Table
-- ===========================================
CREATE TABLE IF NOT EXISTS APP_INVOICE (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    INVOICE_NUMBER VARCHAR(50) NOT NULL UNIQUE,
    USER_ID BIGINT NOT NULL,
    INVOICE_DATE DATE NOT NULL,
    DUE_DATE DATE,
    DESCRIPTION VARCHAR(500),
    AMOUNT DECIMAL(10,2) NOT NULL,
    CURRENCY VARCHAR(3) DEFAULT 'EUR',
    STATUS VARCHAR(20) NOT NULL,
    PDF_PATH VARCHAR(500),
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (USER_ID) REFERENCES APP_USER(ID)
);

CREATE INDEX IF NOT EXISTS IDX_APP_INVOICE_USER_ID ON APP_INVOICE(USER_ID);
CREATE INDEX IF NOT EXISTS IDX_APP_INVOICE_STATUS ON APP_INVOICE(STATUS);
CREATE INDEX IF NOT EXISTS IDX_APP_INVOICE_DATE ON APP_INVOICE(INVOICE_DATE);
